### ISSUE TITLE
templates, enhancement: allow loading of remote template documents

### ISSUE THREAD

**Issue by kohsah** [eXist-db/shared-resources#23]
Currently the `templates:include` and `templates:surround` APIs have the `$path` and `$with` parameter, and this is assumed to be a template file within the same application with a relative path. 

However, in my case I am applying some pre-processing on the template using Mustache and then providing it to eXist. So I want to serve the templates from a different templates server. I found making the $path and $with support `http` paths is very easy. I believe this small change adds a significant improvement to the templating functionality. 

So the call to the template would look something like:
```
<div  data-template="templates:surround" data-template-
     with="http://localhost:9999/templatesServer/templates/page.xml" 
     data-template-at="content">
....
</div>
```

**Comment by joewiz** [comment]
Closed by #24.
