### ISSUE TITLE
highlight + ace prevent jQuery updates

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/shared-resources#26]
@wolfgangmm Would it be possible to wean our apps off the custom highlight jQuery plugin, as it prevents jQuery updates past 1.8? It might also help with using a new ace that fixed some bidi bugs that are bugging exide users. 

The state of js syntax highlighters for XQuery is not great, but if we could expand on this [highlight.js parser](https://github.com/isagalaev/highlight.js/blob/master/src/languages/xquery.js) that would remove one bloc from using html5 and more current js libraries. Since you wrote the current highlighter, do you think thats feasible?

P.S.: In the meantime if we could switch the current attribute from ``data-language="xquery"`` to ``<code class="language-XQuery">`` or ``<code class="xquery">`` we would be closer to html5 recommendations.

**Comment by wolfgangmm** [comment]
`hightlight.js` does work for me, so I'm fine with your suggestion.
