### ISSUE TITLE
abbrev changed

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/shared-resources#36]
as my comment indicates here https://github.com/eXist-db/shared-resources/commit/6d366e0417d7a1bd03276e4168bc0d85d21e9862#r30783263 the abbreviation changed from "shared" to "shared-resources". as the build properties in eXist declare "shared" to be autodeployed, this will cause some builds to fail, see here: https://github.com/eXist-db/exist/blob/develop/build.properties#L33

**Comment by joewiz** [comment]
@mathias-goebel Very sorry, and this isn't the first time I've done this (https://github.com/eXist-db/shared-resources/pull/22). I'm preparing a hotfix that should prevent this from happening in the future.
